### ISSUE TITLE
Lizardfolk Natural Armor and Unarmored Defense

### ISSUE THREAD

**Issue by BobStumpp** [Sklore/HL_DD_5e_Colab#758] opened 2017-11-12 15:27 UTC
Per Jeremy Crawford at Sage Advise, Natural Armor and Unarmored Defense do not stack.  However, if you are Barbarian Lizardfolk with a +2 Dex and a +2 Con, your AC shows as 17, when it should be 15 (Natural Armor - 13, plus Dex).

**Comment by dungeonguru** [comment] 2017-12-08 15:16
Unarmored Defense is code written by Lone Wolf, not the community.  Not sure if we can write an effective workaround on the race or create a Barbarian (and Monk) replacement that includes code for this. Suggest until we can get an answer from LW, you use the adjustment for Armor Class penalty in the adjustment tabs.

**Comment by Namorphus** [comment] 2017-12-09 04:23
Could we check if Unarmored Defense is being applied to the character? Or, if the character's class has a feature unlocked like Unarmored Defense, could we process whether to revert and apply natural armor or leave as is?

**Comment by dungeonguru** [comment] 2017-12-09 12:44
It is possible to check for the hero having the ability Unarmored Defense, it is even possible to detect if the hero has natural armor. The problem is that Unarmored Defense (both Monk and Barbarian) are part of the SRD code that Lone Wolf maintains, the same problem exists for the Sorcerer Draconic Resilence ability. The community could make copies of all 3 of those items with appropriate fixes, but my vote would be to first see if LW would do the heavy lifting - so I put a bug report in and am waiting a response.

**Comment by BobStumpp** [comment] 2017-12-10 19:08
Thanks for the update, and based on the information you have given, I would agree that LW would probably be the right place to have this issue corrected.  Again, thanks.

**Comment by dungeonguru** [comment] 2018-03-12 17:01
LW said they addressed this in one of the last couple of updates, going to close this ticket on the community side.

**Closed by dungeonguru** 2018-03-12 17:01 UTC
Labels: LW Bug, Suspended, bug
