### ISSUE TITLE
Cleric CFV Blessed Strikes Missing

### ISSUE THREAD

**Issue by wjpennington** [Sklore/HL_DD_5e_Colab#950] opened 2020-05-11 19:35 UTC
Class Variant Feature for Cleric: Blessed Strikes 8th-level cleric Divine Domain feature (replaces Divine Strike or Potent Spell casting) Not listed.

When creating Class Variant Ranger, displays  error message that Primal awareness isn't a valid selection because detect magic spell is not covered by license.

![Ranger feature error](https://user-images.githubusercontent.com/65191700/81603839-9c99f600-9394-11ea-914a-c7950403cc56.png)
![missing cleric feature](https://user-images.githubusercontent.com/65191700/81603919-b63b3d80-9394-11ea-81dc-280fe592b77a.png)

**Comment by Fenris447** [comment] 2020-05-19 20:10
Good catches. Will be fixed in next release.

**Comment by Fenris447** [comment] 2020-05-19 23:01
Fixed these descriptions. Closing.

**Comment by Fenris447** [comment] 2020-05-19 23:11
Accidentally closed this instead of a different issue.

**Comment by Fenris447** [comment] 2020-05-20 22:07
The Detect Magic problem is fixed for next release. The missing Cleric feature will take a bit more work but should be ready by the next release as well.

**Comment by Fenris447** [comment] 2020-10-16 18:45
Just to update this, I am likely not going to address the Cleric part until I know it’s being added in Tasha’s.

The problem is that unlike most of the variant features, which replace a specific ability, this replaces either of two abilities, and those two abilities also have separate versions for many of the Cleric subclasses in the Community Pack. So programming this to seek out those various versions AND make it somehow search for them in future subclasses is much more difficult. 

It’s doable, but I will not spend the time on the UA version until I know there’s an official one coming.

**Comment by wjpennington** [comment] 2020-10-16 19:42
That makes perfect sense. With Tasha’s pending arrival, there’s an incredible amount that could be changed.

**Comment by Fenris447** [comment] 2020-10-22 02:28
I couldn't help myself...I figured it out and added it. It'll be in the next release. If you want it now, take the code here and add it to the end of your COM_5ePack_UA - Class Feature Variants.user file (but before "  </document>")
[Blessed Strikes.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/5419651/Blessed.Strikes.txt)

**Closed** 2020-10-22 02:28 UTC
