### ISSUE TITLE
Windvane Spear does wrong damage

### ISSUE THREAD

**Issue by RossRC** [Sklore/HL_DD_5e_Colab#760] opened 2017-12-01 06:59 UTC
The Windvane Spear, from Prince's of the Apocalypse, is supposed to do 1d8+7 damage +1d6 lightning. Instead, it's doing 1d8+71d6 damage.

**Comment by Namorphos** [comment] 2017-12-09 00:34
When is this occurring? Is this on a tablet or desktop/laptop? Do you have the same issue with Tinderstrike (Same (i.e. 1d4+72d6) which is also from PoTA?

**Comment by dungeonguru** [comment] 2017-12-09 03:25
I'll answer for RossRC, everytime in desktop/laptop - can't speak for tablet. The problem is:
<fieldval field="wDamExtra" value="1d6 lightning damage"/>
this should be " plus 1d6 lightnining damage" - the verbiage on the extra damage field should have a space in it so that it doesn't cram it all together. What is happening in RossRC's case is that the spear is doing 1d8+7 base damage and then there's no space before it renders 1d6 lightning damage.  I think the same is happening with Tinderstrike and some other gear here and there.

**Comment by Namorphos** [comment] 2017-12-09 03:54
I think its only in the PoTA files. If more locations are known to have this issue, I can scrub through them. Otherwise, I'll patch up PoTA_Equipment for now.

**Comment by Namorphos** [comment] 2017-12-09 03:58
@dungeonguru for my future reference, I notice most Extra Attack texts have " plus...". Is that a guideline for the community data to follow?

**Comment by dungeonguru** [comment] 2017-12-10 17:54
Merged in with #764

**Closed by dungeonguru** 2017-12-10 17:54 UTC
