### ISSUE TITLE
Uthgardt barbarian error

### ISSUE THREAD

**Issue by dubugz** [Sklore/HL_DD_5e_Colab#864] opened 2018-07-28 16:33 UTC
Created halfling uthgardt (yes I know. Canon) but when I choose stout then go to the play tab survival is replaced by athletics   It’s fine with other races

**Comment by dungeonguru** [comment] 2018-07-28 16:51
When you say "halfling uthgardt" is that you made a new character, chose the Uthgardt Barbarian background and then halfling with subrace Stout or are you doing something different? 

The background should give both Athletics and Survival skill proficiency - I don't see where it would update the In-Play tab at all.  The stout halfling subraces has no scripts that add or remove skills, none.

**Comment by dubugz** [comment] 2018-07-28 16:55
Email me I will send you a screen shot

**Comment by dubugz** [comment] 2018-07-28 17:33
Update:  created new stout halfling on iPad. Background of uthgardt. When I go to the tab that says play the word survival is replaced by acrobatics

**Comment by dungeonguru** [comment] 2018-07-29 11:29
I'm going to have to ask assistance for any of the other contributors with an iPad to verify what's going on. I can't replicate on a PC and don't have an iPad. I know there have been client issues on LW's side for the past patch or two, this might need to reach out to their tech support.

**Comment by Sklore** [comment] 2018-07-29 12:02
I don't have one either sorry.

**Comment by LordMorin** [comment] 2018-08-02 21:54
Well, I finally got around to looking at this issue on my iPad, and can replicate the issue. I can't find the source of the issue yet through the editor. My next stage is to open the Background .user file in Notepad++ and see what I can find this way.

Acrobatics is replacing Survival on the Inplay's Skill window . . .

**Comment by LordMorin** [comment] 2018-08-02 22:00
Iteresting, I switched back ground, and then disables SCAG Backgrounds all together and I get the same issue.

My next step will be to create a test version of the Community Pack for the iPad without SCAG in it and see if I get the same issue.

I'll also try it with other races and see what happens.

**Comment by dungeonguru** [comment] 2018-08-02 22:08
Before you go that far, does it do it without the community pack loaded? It might not be community related at all.

**Comment by LordMorin** [comment] 2018-08-02 22:11
Haven't tried it yet. I did discover that the issue occurs for both the Stout Halfling and the Strongheart Halfling, but not the Lightfoot Halfling. Both the problem children are supposed to be from 5E Players Handbook. Looking into them at the moment. So far I'm only seeing the Stout Halfling in the .user file . . .

**Comment by LordMorin** [comment] 2018-08-02 22:17
Found the Strongheart Halfling in SCAG - Races. It's source is wrong. Probably just copied from 5E Players Handbook without changing the source. So far no sign of the issue. Next I'll go through the actual .user files in Notepad++.

**Comment by dungeonguru** [comment] 2018-08-02 22:19
Not much to it. It bootstraps Stout Resilience and adds +1 to CON. Nothing references skills at all.

**Comment by LordMorin** [comment] 2018-08-02 22:25
I tried it with other subraces from the 5E PHB file. The wood elf, drow, and forest gnome work fine. The mountain dwarf has the same issue though.

**Comment by dungeonguru** [comment] 2018-08-02 22:39
I think that both the mountain dwarf and stout halfling grant advantage to saves vs. poison to all save, but the others don't. Could the added * on the saves be pushing the skill names down or sideways? Can you remove the advantage script and try?

**Comment by LordMorin** [comment] 2018-08-02 23:10
OK, what I've got so far (working with the Stout Resilience ability script.

1) Deleted script (after backing it up).
- Issue with Survival being renamed to Acrobats gone.
2) Put script back and commented out the $Situational part
- Issue returned
3) Uncommented #Situational and commented out the pushtags portion
- Issue resolved.

- The issue seems to me in the "perform hero.pushtags[DamageRes.?]

- Now I need to figure out why.

**Comment by LordMorin** [comment] 2018-08-02 23:31
I've tried timing changes.
I've tried changing the "perform hero.pushtags[DamageRes.?]" to "perform hero.assign[DamageRes.dtPoison]" and am still getting the same issue. :(

**Comment by shadowchemosh** [comment] 2018-08-05 02:10
This is a UI bug in the iPad itself (most likely a memory pointer) that gets confused when the "Resistance/Immunity" section suddenly shows up below the skills.

Will try and write this up and send it into Dave soon.

![image-1-1](https://user-images.githubusercontent.com/7717785/43682002-c4a0e814-982a-11e8-9bfe-3380209040a8.jpg)

**Comment by dubugz** [comment] 2020-01-28 13:17
Just an FYI, because it doesn't look like this got fixed yet.  With the last update for the iPad, now it shows Acrobatics & Animal handling replacing "Survival & Tools  under Skills

**Comment by Fenris447** [comment] 2020-01-28 19:30
@dungeonguru Did you happen to send this bug in? I have half a mind to close it, since it’s not a Community Pack bug.

**Comment by dungeonguru** [comment] 2020-01-28 19:56
I would suggest dubugz or someone that has an iPad to test with enter an official LW ticket if shadowchemosh doesn't get back, community can't fix this one so closing the ticket is proper. It might not hurt to open a Known Bugs wiki topic or something to keep in on the radar. This won't be the last time an iPad bug gets tossed this way. There are a few closed tickets that were related to iPad bugs.

**Comment by LordMorin** [comment] 2020-01-28 20:08
As far as I know, the iPad app is no longer supported and will not be getting updates . . .

**Comment by CharlieLuce** [comment] 2020-01-28 23:33
> As far as I know, the iPad app is no longer supported and will not be getting updates . . .

That's my understanding as well. Apple has decided that Hero Lab data packages are game DLC and game DLC for an iPad App can only be purchased through the Apple Store so that Apple gets its 30% cut.

**Comment by dubugz** [comment] 2020-01-29 18:21
I emailed support, and this was what i was told **We are still supporting the iPad, although there have been some issues in the past few months in regards to having the patches and updates on the platform for the past few months. We are working to find ways to get past this obstacle but it has been something of an ordeal.**

I sent them the info on this ticket. 

Thanks everyone. 
D

**Comment by Fenris447** [comment] 2020-10-16 19:04
Closing this. It’s not a bug in the Community Pack so not much we can do about it.

**Closed by Fenris447** 2020-10-16 19:04 UTC
Labels: LW Bug, help wanted, iPad Help
