### ISSUE TITLE
COM_5ePack_TYP - All.user error

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#876] opened 2018-10-01 17:03 UTC
This issue started for me after the last HL update.

Unfortunately for me, the hard drive I had HeroLab installed on on my main system bought the farm just after that. I just re-installed. I seem to have recovered99% of everything, but am still getting the following error.

> The data files could not be loaded due to errors. Hero Lab will now attempt to load them in recovery mode. Once loaded, you can access the editor as normal to correct any errors.
> 
> The following errors occurred:
> 
> File: COM_5ePack_TYP - All.user (line 2026) - Thing - Invalid unique id 'r5CTYPFourArmedGarg' for attribute 'id'

**Comment by dungeonguru** [comment] 2018-10-01 17:07
I thought @shadowchemosh recently uploaded a new file with the fix - you might just need to redownload the github files or quick-edit it for yourself. 

The issue is that that ID is over the new 17 character limit. I think Tim renamed it r5CTYP4ArmedGarg or something.

**Comment by LordMorin** [comment] 2018-10-01 17:08
Thx, I am in the midst of doing that atm. :)

**Comment by Fenris447** [comment] 2020-01-11 05:47
This is fixed in the current files and will be included in the next release.

**Closed by Fenris447** 2020-01-11 05:47 UTC
