### ISSUE TITLE
Class levels need a source checked or they continue to show after source is checked.

### ISSUE THREAD

**Issue by Enforcer84** [Sklore/HL_DD_5e_Colab#520] opened 2016-11-27 07:37 UTC
Was just playing around and I noticed when I unchecked everything the following classes still showed in my list: Alchemist, Alchemist, Blood Hunter, Mystic, and Ranger (Sept 2016).

popped the user files open and saw that while the classes were all correctly sourced the "class levels" were all unchecked. Checking the source box for the class levels feature made them not load when their source was unchecked. (if that makes any sense) 

Also...I appended the non-magical alchemist thus so I was no longer confused as to which alchemist was which.

**Comment by LordMorin** [comment] 2016-11-27 07:41
This has been fixed, along with a bunch more such related issues, and will
be available in the next update (or for download from the GIT site).

I discovered a few more similar issues with Goblin deities. The issue is
sources weren't set on these items.

**Comment by Sklore** [comment] 2016-11-27 10:03
Yeah this one should be fixed in the next release.

**Closed by Sklore** 2016-11-27 10:03 UTC
