### ISSUE TITLE
KP Midgard Heroes

### ISSUE THREAD

**Issue by HippyCraig** [Sklore/HL_DD_5e_Colab#499] opened 2016-11-09 03:15 UTC
Not sure if this is an issue but wanted to post it, under Darakhul Ghoul, under weapons the names look off, not sure if this is right or not, see attached picture.

![hl-fix](https://cloud.githubusercontent.com/assets/17074456/20126136/c68a7ece-a600-11e6-830a-c34f54d21b95.png)

**Comment by TheEnthusiast** [comment] 2016-11-26 00:59
@HippyCraig , @Sklore 

From what I can see on COM_5ePack_Private_MH5e - All.user , these are tags pointing to weapons that do not exist. I do not have the sourcebook so I cannot say for sure what was intended here. The race does have a byte attack, so perhaps it's supposed to have something more?

**Comment by Sklore** [comment] 2016-11-27 03:38
Thanks guys. 

Can't honestly remember why we did that. Removing it works fine. Have replaced with standard bite. Stats are all good.

**Comment by Sklore** [comment] 2016-11-27 03:40
Will be fixed in the next release.

**Closed by Sklore** 2016-11-27 03:40 UTC
Labels: bug

**Comment by HippyCraig** [comment] 2016-11-27 04:06
Cool

**Comment by HippyCraig** [comment] 2016-11-27 04:07
Are the user files and the files for the encounter builder both effected by this ?

**Comment by Sklore** [comment] 2016-11-27 12:51
Encounter builder?

**Comment by HippyCraig** [comment] 2016-11-28 15:09
From the Game Master menu there is the Encounter Builder, that usually has the portfolios of the standard monsters created, will updating the source update those as well?

**Comment by Sklore** [comment] 2016-11-29 11:46
Yeah that's just a list linking all of the content t that exists in the stock files. Those just files are effectively just links to the use files so updating it will flow through.
