### ISSUE TITLE
Land Druid circles missing

### ISSUE THREAD

**Issue by DWiz135** [Sklore/HL_DD_5e_Colab#713] opened 2017-08-22 18:08 UTC
My wife has a land druid and it looks like she can no longer choose a circle such as arctic, coast, etc anymore after the update unless we're missing something. I've attached a screenshot of what it looked like _prior_ to the update where you could select the circle @ level 3. Are we missing something or is this broken for others as well?

![image](https://user-images.githubusercontent.com/31254424/29580119-80895d52-873a-11e7-932d-297aed235662.png)

**Comment by Sklore** [comment] 2017-08-22 21:54
Certainly looks like something is broken. It's not on our end though. The Community Pack only control the non SRD circles. Circle of the Land is maintained by LWD. I have submitted a bug report to them given you have noticed the error post the 2.0 upgrade. Will post the results here once available.

**Comment by dungeonguru** [comment] 2017-08-22 23:06
Actually, I think it might be COM_5ePack_EN5 - 31 - Forgotten Lore - Divine.user throwing a wrench into things.  The thing: c5CDrdCir  replaces the druid circle spells, and has a source of EN5_31 (En5ider 31 - Forgotten Lore - Divine) .  Two workarounds: 
1. Turn on the En5ider 31 source.
2. Remove the En5ider 31 file. 

Long-term, probably have to remove the usesource field on c5CDrdCir or have it point to the PHB.

**Comment by HRogue135** [comment] 2017-08-22 23:19
It looks like the workaround of turning on the En5ider 31 source works and actually brings back the Circle Spells option. So, it appears that the bug may be in the COM_5ePack_EN5 - 31 - Forgotten Lore - Divine.user file, rather than in the core LWD code.

**Comment by Sklore** [comment] 2017-08-23 07:49
Ok that we need to fix. Quickly.

**Comment by dungeonguru** [comment] 2017-08-23 11:22
From some testing, I think all you need to do is remove the replace option on c5CDrdCir, this might break the en5ider article a bit, but that keeps the SRD intact without introducing the Urban circle spells into the SRD choice lists. 

The problem is then we'll get a ticket that the en5ider article is broken, which is something we're willing to deal with?

**Comment by Sklore** [comment] 2017-08-23 12:32
Yeah I did the same thing. It's obviously more important for the SRD content to work than the En5ider so it's a short term solution that likely will impact no one at this stage but I do wonder how we will fix it.

**Comment by dungeonguru** [comment] 2017-08-23 13:41
I don't have access to en5ider so I'm not sure what the fix is for the en5ider article. Whoever authored it will have to speak up. I do know that if you put the fix in for the SRD that is proposed, it doesn't break the new custom circle "Circle of Land: Urban" - the new circle doesn't even utilize the expanded Circle Spells ability - it replaces it with a different ability. I think this was an attempt to expand the Circle Spells list to include the Urban spells, without swapping out the 14th level ability (the new custom circle replaces "Nature's Sanctuary" with "Thousand Forms").

**Comment by Sethvir** [comment] 2017-08-23 16:39
True statement as i recall.  I was the one that attempted this.  I dont
have the article in front of me at the moment.

**Comment by Cormath** [comment] 2017-08-23 23:03
Got it working..

   1. Downloaded as a full zip file from website
   2. Unzipped and copied all the files out into the base Hero Labs DnD 5e
   folder
   3. C:\ProgramData\Hero Lab\data\5e
   4. Has to be in the base 5e folder (no subfolders), so have to flatted
   the zip file folder structure
   5. The zipped filenames start "COD" which is unique filenames from the
   Hero Labs files (no overwrite)
   6. Restarted Hero Lab, and it worked.

**Comment by dungeonguru** [comment] 2017-08-26 18:24
Has anyone uploaded a fix? 
I had an idea, but not enough scripting knowledge to pull it off. 

If interested, my idea:

1. Remove the source restriction from EN31 or replace it with the PHB. 
2. Remove the references and verbiage to Urban spells in the description and remove the choice from the array (usrArray - index 8).
3. In an eval script, check to see if Source.EN31 tag is checked on the hero. If it is checked, then add the Urban verbiage to the description text. Add the Urban choice to the end of the choice array (add back the usrArray index 8 option). 

This would imitate the source lockdown that is desired, but I'm not sure how to manipulate the usrArray fields. Someone else might though.

**Comment by HRogue135** [comment] 2017-09-10 19:31
Is there any update on a fix for this issue?

**Comment by dungeonguru** [comment] 2017-09-10 19:38
I was waiting on some input here. We can remove the "replace" on the new ability, but then you lose the Underdark and Urban circles until the UA code is rewritten, or we can remove the source restriction and then everyone gets the Underdark and Urban circles. Option two is the least troublesome to me. It just adds a few unobtrusive options to a normal land druid.

**Comment by dungeonguru** [comment] 2017-09-10 20:19
Actually, I have uploaded my fixed version. If EN5ider article 31 is not checked, it won't load the Urban spell list. If it is checked, it adds the missing spell list text (for both Underdark and Urban).

If the En5ider article 31 is not checked, the land circle spells show up as expected.

**Comment by dungeonguru** [comment] 2017-09-10 20:25
Merged a fix into code base - if we want to push this fix, please do so, there are a few other fixes that are in the master code base, but they have been tested and should not affect/break anything else.

**Comment by dungeonguru** [comment] 2017-09-11 16:36
Fix is merged in #722

**Closed by dungeonguru** 2017-09-11 16:36 UTC
Labels: bug

**Comment by Sklore** [comment] 2017-09-12 22:26
Thanks @dungeonguru 
Apologies I am well distracted atm with the pending RW CM release. 
Will look to throw together a bug update in the coming week and get it pushed out.
