### ISSUE TITLE
A multiclass monk/druid cannot see unarmed strike in wild shape request. 

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1003] opened 2021-05-22 12:29 UTC
I cannot see unarmed strike in wild shape even if I add a monk class to each form. I came up with 3 ways to do this. Hope one of these would work for you. 

Adjustment
Unarmed attack pOMEUnarmedAttack
This adjustment is meant to add an unarmed strike to wild shape users.                                place in desc

Bootstrap wUnarmed                                                                                                                 put in bootstrap

Wondrous 
Item of creating Unarmed Attack ioOMEWitemUnarmed                                                                         
This can cause a unarmed strike to show in wildshaped forms for those who also follow the way of monk.

Bootstrap wUnarmed
Tags Group Id Tag Id
Helper EquipMag
Helper ShowSpec
GearType gWondrous
Helper EquipAvail
Helper AlwaysAvail

Last one is a actual weapon.
Unarmed Strike wOMEMelWepUnarmed
You'll need to extend that to nat weapon
Extend wOMEMelWepUnarmed BaseNatWep                                                Needed for unarmed boost items

desc
This remains the only way to enchant an unarmed strike. This item can be a cetus, a handwrap or even knuckles. Being a weapon it can take any weapon efffects such as from Hex, Hunter's Mark and cleric's Divine Strike.

Damage Dice 1
Damage dice type 4
Simple prof and also check always proficient. also damage doesn't change with size.                  

Now you should be able to get Adamantine or silvered unarmed strike as well as that will show on the table now. One oddity, Using the proposed change to Fisticuffs unarmed style which add +2 damage to unarmed somehow remove the +2 from any unarmed strike made this way from Adamantine, vicious and silvered. I'll use a temporary damage adjustment or just rename a regular unarmed strike to include Adamantine say.

**Comment by Fenris447** [comment] 2021-10-13 23:25
Adding an unarmed strike is easy enough. There's even an option at the bottom of the Configure Hero screen called "Show Unarmed (in weapons)" that will do this. The problem is with applying all of the numerous unarmed strike bonuses that the Monk confers to an unarmed strike on the minion Wild Shape. That's a big, big task, and not one I'm inclined to tackle. If you can figure it out in a simple way (like a single adjustment) that doesn't require a rewrite of the whole Monk class and all its relevant features, I'd include it in the pack.

**Comment by Fenris447** [comment] 2022-01-04 22:42
I did just think of a way to do this, using the bootstrap on an adjustment. Put a Custom.____ tag on the added Unarmed, and then have the adjustment pull all the fields from the master's unarmed strike and apply them to the bootstrapped, minion's unarmed strike. You'd want to do it super late in timing, so all the Monk features can already be applied in the master.

**Comment by Fenris447** [comment] 2022-02-01 00:42
I've worked on this for a few hours and can't get it to work, unfortunately. Here's where I landed, but it still doesn't pull stuff over to the minion. I'm comfortable leaving it up to the player to use adjustments on the Wild Shape minion for now. But if you can take this further to the point where it's working, feel free to submit the fix as a new issue!

First 500
`    ~ Check to see if we're a monk before we add Unarmed attacks
    ~ If we're not enabled, get out now
    doneif (field[pIsOn].value = 0)
    doneif (hero.tagis[system_tag.minion] = 0)
    doneif (master.tagcount[Classes.Monk] = 0)

    field[pMinimum].value = 1`


Bootstrap wUnarmed at First 501 with condition
`fieldval:pMinimum = 1`

Final 12000 (this is where I think the problem lies)
`    ~ Pull monk's unarmed strike stuff over to the Wild Shape
    ~ If we're not enabled, get out now
    doneif (field[pIsOn].value = 0)
    doneif (hero.tagis[system_tag.minion] = 0)
    doneif (field[pMinimum].value <> 1)

    perform master.childfound[wUnarmed].setfocus

    hero.childfound[wUnarmed].field[wDieSize].value = maximum(focus.field[wDieSize].value,hero.childfound[wUnarmed].field[wDieSize].value)

    hero.childfound[wUnarmed].field[dmmBonus].value = maximum(focus.field[dmmBonus].value,hero.childfound[wUnarmed].field[dmmBonus].value)

    hero.childfound[wUnarmed].field[atmBonus].value = maximum(focus.field[atmBonus].value,hero.childfound[wUnarmed].field[atmBonus].value)`

**Closed by Fenris447** 2022-02-01 00:42 UTC
Labels: Enhancement

**Comment by Dragon5e** [comment] 2022-02-01 02:33
Gosh that been a while. I got all my adjustments in a single file which I sent.
p5cUnarmedadj in Adjustment add unarmed strike to wildshape
WOMEcustunstr in Weapon allow me to you know actually enchant that unarmed strike. 
wOMEcustunstr in Extend Thing add base nat weapon to unarmed so I can use insignia of claws with any unarmed strike
iowondrunarmed in Wondrous is another way of adding unarmed strike to wildshape

Ok look at this bear wildshape with Eldtrich Claws(tattoo) and 2 insignia of claws
Bite (Brown bear) 1d8+6 piercing Melee +8
Claws (Brown bear) 2d6+6 slashing Melee +8
Unarmed attack 1d4+7 bludgeoning Melee +9 with that adjustment. Yes that is correct. apparently the bear is off by one. 
Unarmed strike (M) 1d4+7 if you add one monk to the bear. 1 +7 if you skip the monk but still use that weapon.
With no tattoo or not wearing insignia?
Bite (Brown bear) 1d8+4 piercing Melee +6
Claws (Brown bear) 2d6+4 slashing Melee +6
Unarmed attack 1d4+5 bludgeoning Melee +7 with that adjustment. Yes that is correct. apparently the bear is off by one. 
Unarmed strike (M) 1d4+5 if you add one monk to the bear. 1 +5 if you skip the monk but still use that weapon.

 What you use. Depend on what you need I guess. Me I like to see proper AC and weapons on the wildshape. I have not figure out how to add AC with the parent monk yet. 
I hope you can use some of this.     On Monday, January 31, 2022, 06:42:31 PM CST, Fenris447 ***@***.***> wrote:  
 
 


I've worked on this for a few hours and can't get it to work, unfortunately. Here's where I landed, but it still doesn't pull stuff over to the minion. I'm comfortable leaving it up to the player to use adjustments on the Wild Shape minion for now. But if you can take this further to the point where it's working, feel free to submit the fix as a new issue!

First 500
` ~ Check to see if we're a monk before we add Unarmed attacks
~ If we're not enabled, get out now
doneif (field[pIsOn].value = 0)
doneif (hero.tagis[system_tag.minion] = 0)
doneif (master.tagcount[Classes.Monk] = 0)
field[pMinimum].value = 1`
Bootstrap wUnarmed at First 501 with condition
fieldval:pMinimum = 1

Final 12000 (this is where I think the problem lies)
` ~ Pull monk's unarmed strike stuff over to the Wild Shape
~ If we're not enabled, get out now
doneif (field[pIsOn].value = 0)
doneif (hero.tagis[system_tag.minion] = 0)
doneif (field[pMinimum].value <> 1)
perform master.childfound[wUnarmed].setfocushero.childfound[wUnarmed].field[wDieSize].value = maximum(focus.field[wDieSize].value,hero.childfound[wUnarmed].field[wDieSize].value)hero.childfound[wUnarmed].field[dmmBonus].value = maximum(focus.field[dmmBonus].value,hero.childfound[wUnarmed].field[dmmBonus].value)hero.childfound[wUnarmed].field[atmBonus].value = maximum(focus.field[atmBonus].value,hero.childfound[wUnarmed].field[atmBonus].value)`
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
   
  <thing id="rFireElem1" name="Fire Elemental" compset="Race" replaces="rFireElem">
    <fieldval field="rHitDice" value="12"/>
    <fieldval field="rHPStart" value="102"/>
    <fieldval field="rCR" value="5.0"/>
    <fieldval field="rMultiatt" value="The elemental makes two touch attacks."/>
    <fieldval field="rSpeed" value="50"/>
    <fieldval field="rDEX" value="7"/>
    <fieldval field="rCON" value="6"/>
    <fieldval field="rINT" value="-4"/>
    <fieldval field="rCHA" value="-3"/>
    <tag group="CondImm" tag="pcnUnconc" name="Unconscious" abbrev="Unconscious"/>
    <tag group="DamComRes" tag="dcAtkNonMa" name="Bludgeoning, piercing, and slashing from nonmagical attacks" abbrev="Bludgeoning, piercing, and slashing from nonmagical attacks"/>
    <tag group="DamageImm" tag="dtFire" name="Fire" abbrev="Fire"/>
    <tag group="DamageImm" tag="dtPoison" name="Poison" abbrev="Poison"/>
    <tag group="RaceSize" tag="Large1" name="Large" abbrev="Large"/>
    <tag group="RaceType" tag="NPC" name="NPC Race" abbrev="NPC Race"/>
    <tag group="Alignment" tag="NeutralGE" name="Neutral" abbrev="N"/>
    <tag group="Alignment" tag="NeutralLC" name="Neutral" abbrev="N"/>
    <tag group="CondImm" tag="pcnExhaust" name="Exhaustion" abbrev="Exhaustion"/>
    <tag group="CondImm" tag="pcnGrapple" name="Grappled" abbrev="Grappled"/>
    <tag group="CondImm" tag="pcnParaly" name="Paralyzed" abbrev="Paralyzed"/>
    <tag group="CondImm" tag="pcnPetri" name="Petrified" abbrev="Petrified"/>
    <tag group="CondImm" tag="pcnPoison" name="Poisoned" abbrev="Poisoned"/>
    <tag group="CondImm" tag="pcnProne" name="Prone" abbrev="Prone"/>
    <tag group="CondImm" tag="pcnRestr" name="Restrained" abbrev="Restrained"/>
    <bootstrap thing="tpElementa"></bootstrap>
    <bootstrap thing="lIgnan"></bootstrap>
    <bootstrap thing="raDarkVis">
      <autotag group="Value" tag="60"/>
      </bootstrap>
    <bootstrap thing="raFiEFiFor"></bootstrap>
    <bootstrap thing="raFiEIllum"></bootstrap>
    <bootstrap thing="raFiEWaSus"></bootstrap>
    <bootstrap thing="xMultiatt"></bootstrap>
    <bootstrap thing="wOtherMel">
      <autotag group="AttackTarg" tag="1Target"/>
      <autotag group="DamageOver" tag="aDEX"/>
      <autotag group="DamageType" tag="dtFire"/>
      <autotag group="MelAttOver" tag="aDEX"/>
      <assignval field="livename" value="Touch"/>
      <assignval field="sbName" value="Touch"/>
      <assignval field="wAttackEff" value="If the target is a creature or a flammable object, it ignites. Until a creature takes an action to douse the fire, the target takes 5 (1d10) fire damage at the start of each of its turns."/>
      <assignval field="wDieCount" value="2"/>
      <assignval field="wDieSize" value="6"/>
      </bootstrap>
    </thing>

**Comment by Dragon5e** [comment] 2022-02-01 03:08
Mild error on my last reply. Apparently it's not enough to just remove the eldritch claws. You also have to click the attuned button or it will add the +1 to any unarmed strike even if not wearing it. With that done all the weapons match up. 


     On Monday, January 31, 2022, 06:42:31 PM CST, Fenris447 ***@***.***> wrote:  
 
 


I've worked on this for a few hours and can't get it to work, unfortunately. Here's where I landed, but it still doesn't pull stuff over to the minion. I'm comfortable leaving it up to the player to use adjustments on the Wild Shape minion for now. But if you can take this further to the point where it's working, feel free to submit the fix as a new issue!

First 500
` ~ Check to see if we're a monk before we add Unarmed attacks
~ If we're not enabled, get out now
doneif (field[pIsOn].value = 0)
doneif (hero.tagis[system_tag.minion] = 0)
doneif (master.tagcount[Classes.Monk] = 0)
field[pMinimum].value = 1`
Bootstrap wUnarmed at First 501 with condition
fieldval:pMinimum = 1

Final 12000 (this is where I think the problem lies)
` ~ Pull monk's unarmed strike stuff over to the Wild Shape
~ If we're not enabled, get out now
doneif (field[pIsOn].value = 0)
doneif (hero.tagis[system_tag.minion] = 0)
doneif (field[pMinimum].value <> 1)
perform master.childfound[wUnarmed].setfocushero.childfound[wUnarmed].field[wDieSize].value = maximum(focus.field[wDieSize].value,hero.childfound[wUnarmed].field[wDieSize].value)hero.childfound[wUnarmed].field[dmmBonus].value = maximum(focus.field[dmmBonus].value,hero.childfound[wUnarmed].field[dmmBonus].value)hero.childfound[wUnarmed].field[atmBonus].value = maximum(focus.field[atmBonus].value,hero.childfound[wUnarmed].field[atmBonus].value)`
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
